apiVersion: v1
kind: Pod
metadata:
  name: match-app
  labels:
    app: match-app
spec:
  containers:
    - name: match
      image: match:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 7903