apiVersion: v1
kind: Service
metadata:
  name: match-service
spec:
  selector:
    app: match-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7903
      nodePort: 30903
  type: NodePort