apiVersion: v1
kind: Service
metadata:
  name: site-service
spec:
  selector:
    app: site-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7901
      nodePort: 30901
  type: NodePort