apiVersion: v1
kind: Pod
metadata:
  name: sport-app
  labels:
    app: sport-app
spec:
  containers:
    - name: sport
      image: sport:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 7902