apiVersion: v1
kind: Service
metadata:
  name: sport-service
spec:
  selector:
    app: sport-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7902
      nodePort: 30902
  type: NodePort