apiVersion: v1
kind: Service
metadata:
  name: planning-service
spec:
  selector:
    app: planning-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7904
      nodePort: 30904
  type: NodePort